kind: pipeline
type: docker
name: build

steps:
  - name: push
    image: plugins/docker
    settings:
      username: 100020182378
      password: 5201314123Huang!
      registry: ccr.ccs.tencentyun.com
      repo: ccr.ccs.tencentyun.com/cc_server/backend
      tags: latest
      dockerfile: ./Dockerfile

trigger:
  branch:
  - master
  event: 
  - push

--- 

kind: pipeline
type: docker
name: deploy

clone:
  disable: true

depends_on:
  - build
steps:
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 43.136.64.220
      username: root
      password: 5201314123Huang!
      port: 22
      command_timeout: 5m
      script:
      - docker pull ccr.ccs.tencentyun.com/cc_server/backend:latest
      - docker rm -f cc_server_backend || true # 这里这样是因为如果不存在docker-demo，rm会报错
      - docker run -itd -p 8065:8065 --name cc_server_backend ccr.ccs.tencentyun.com/cc_server/backend