kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
  event:
    - push

pipeline:
  # test:
  #   image: golang
  #   environment:
  #     - GOPROXY=https://goproxy.cn
  #   commands:
  #     - go test
  
  publish:
    image: plugins/docker
    settings:
      username: 100020182378
      password: 5201314123Huang!
      registry: ccr.ccs.tencentyun.com
      repo: ccr.ccs.tencentyun.com/cc_server-ci/backend
      tags: ${DRONE_TAG}
      dockerfile: ./Dockerfile

  deploy:
    depends_on: [ publish ]
    image: appleboy/drone-ssh
    host:
      - 22
    username: root
    password: 5201314123Huang!
    command_timeout: 60
    script:
      - docker pull ccr.ccs.tencentyun.com/cc_server/backend:latest
      - docker rm -f cc_server_backend || true # 这里这样是因为如果不存在docker-demo，rm会报错
      - docker run -itd -p 8065:8065 --name cc_server_backend ccr.ccs.tencentyun.com/cc_server/backend