version: '3.7'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 5201314123Huang!
      MYSQL_DATABASE: cc_server
    ports:
      - 3306:3306
    volumes:
      - /data/mysql:/var/lib/mysql
